// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"todopoint/common/db/ent/pointinfo"
	"todopoint/common/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PointInfoDelete is the builder for deleting a PointInfo entity.
type PointInfoDelete struct {
	config
	hooks    []Hook
	mutation *PointInfoMutation
}

// Where appends a list predicates to the PointInfoDelete builder.
func (pid *PointInfoDelete) Where(ps ...predicate.PointInfo) *PointInfoDelete {
	pid.mutation.Where(ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PointInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pid.sqlExec, pid.mutation, pid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PointInfoDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PointInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pointinfo.Table, sqlgraph.NewFieldSpec(pointinfo.FieldID, field.TypeInt))
	if ps := pid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pid.mutation.done = true
	return affected, err
}

// PointInfoDeleteOne is the builder for deleting a single PointInfo entity.
type PointInfoDeleteOne struct {
	pid *PointInfoDelete
}

// Where appends a list predicates to the PointInfoDelete builder.
func (pido *PointInfoDeleteOne) Where(ps ...predicate.PointInfo) *PointInfoDeleteOne {
	pido.pid.mutation.Where(ps...)
	return pido
}

// Exec executes the deletion query.
func (pido *PointInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pointinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PointInfoDeleteOne) ExecX(ctx context.Context) {
	if err := pido.Exec(ctx); err != nil {
		panic(err)
	}
}
