// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"todopoint/banking/models/ent/bankaccount"
	"todopoint/banking/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BankAccountUpdate is the builder for updating BankAccount entities.
type BankAccountUpdate struct {
	config
	hooks    []Hook
	mutation *BankAccountMutation
}

// Where appends a list predicates to the BankAccountUpdate builder.
func (bau *BankAccountUpdate) Where(ps ...predicate.BankAccount) *BankAccountUpdate {
	bau.mutation.Where(ps...)
	return bau
}

// SetUserID sets the "user_id" field.
func (bau *BankAccountUpdate) SetUserID(s string) *BankAccountUpdate {
	bau.mutation.SetUserID(s)
	return bau
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (bau *BankAccountUpdate) SetNillableUserID(s *string) *BankAccountUpdate {
	if s != nil {
		bau.SetUserID(*s)
	}
	return bau
}

// SetBankName sets the "bank_name" field.
func (bau *BankAccountUpdate) SetBankName(s string) *BankAccountUpdate {
	bau.mutation.SetBankName(s)
	return bau
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (bau *BankAccountUpdate) SetNillableBankName(s *string) *BankAccountUpdate {
	if s != nil {
		bau.SetBankName(*s)
	}
	return bau
}

// SetBankAccount sets the "bank_account" field.
func (bau *BankAccountUpdate) SetBankAccount(u uuid.UUID) *BankAccountUpdate {
	bau.mutation.SetBankAccount(u)
	return bau
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (bau *BankAccountUpdate) SetNillableBankAccount(u *uuid.UUID) *BankAccountUpdate {
	if u != nil {
		bau.SetBankAccount(*u)
	}
	return bau
}

// SetCreatedAt sets the "created_at" field.
func (bau *BankAccountUpdate) SetCreatedAt(t time.Time) *BankAccountUpdate {
	bau.mutation.SetCreatedAt(t)
	return bau
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bau *BankAccountUpdate) SetNillableCreatedAt(t *time.Time) *BankAccountUpdate {
	if t != nil {
		bau.SetCreatedAt(*t)
	}
	return bau
}

// Mutation returns the BankAccountMutation object of the builder.
func (bau *BankAccountUpdate) Mutation() *BankAccountMutation {
	return bau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bau *BankAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bau.sqlSave, bau.mutation, bau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bau *BankAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := bau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bau *BankAccountUpdate) Exec(ctx context.Context) error {
	_, err := bau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bau *BankAccountUpdate) ExecX(ctx context.Context) {
	if err := bau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bau *BankAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bankaccount.Table, bankaccount.Columns, sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeInt))
	if ps := bau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bau.mutation.UserID(); ok {
		_spec.SetField(bankaccount.FieldUserID, field.TypeString, value)
	}
	if value, ok := bau.mutation.BankName(); ok {
		_spec.SetField(bankaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := bau.mutation.BankAccount(); ok {
		_spec.SetField(bankaccount.FieldBankAccount, field.TypeUUID, value)
	}
	if value, ok := bau.mutation.CreatedAt(); ok {
		_spec.SetField(bankaccount.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bau.mutation.done = true
	return n, nil
}

// BankAccountUpdateOne is the builder for updating a single BankAccount entity.
type BankAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BankAccountMutation
}

// SetUserID sets the "user_id" field.
func (bauo *BankAccountUpdateOne) SetUserID(s string) *BankAccountUpdateOne {
	bauo.mutation.SetUserID(s)
	return bauo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (bauo *BankAccountUpdateOne) SetNillableUserID(s *string) *BankAccountUpdateOne {
	if s != nil {
		bauo.SetUserID(*s)
	}
	return bauo
}

// SetBankName sets the "bank_name" field.
func (bauo *BankAccountUpdateOne) SetBankName(s string) *BankAccountUpdateOne {
	bauo.mutation.SetBankName(s)
	return bauo
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (bauo *BankAccountUpdateOne) SetNillableBankName(s *string) *BankAccountUpdateOne {
	if s != nil {
		bauo.SetBankName(*s)
	}
	return bauo
}

// SetBankAccount sets the "bank_account" field.
func (bauo *BankAccountUpdateOne) SetBankAccount(u uuid.UUID) *BankAccountUpdateOne {
	bauo.mutation.SetBankAccount(u)
	return bauo
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (bauo *BankAccountUpdateOne) SetNillableBankAccount(u *uuid.UUID) *BankAccountUpdateOne {
	if u != nil {
		bauo.SetBankAccount(*u)
	}
	return bauo
}

// SetCreatedAt sets the "created_at" field.
func (bauo *BankAccountUpdateOne) SetCreatedAt(t time.Time) *BankAccountUpdateOne {
	bauo.mutation.SetCreatedAt(t)
	return bauo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bauo *BankAccountUpdateOne) SetNillableCreatedAt(t *time.Time) *BankAccountUpdateOne {
	if t != nil {
		bauo.SetCreatedAt(*t)
	}
	return bauo
}

// Mutation returns the BankAccountMutation object of the builder.
func (bauo *BankAccountUpdateOne) Mutation() *BankAccountMutation {
	return bauo.mutation
}

// Where appends a list predicates to the BankAccountUpdate builder.
func (bauo *BankAccountUpdateOne) Where(ps ...predicate.BankAccount) *BankAccountUpdateOne {
	bauo.mutation.Where(ps...)
	return bauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bauo *BankAccountUpdateOne) Select(field string, fields ...string) *BankAccountUpdateOne {
	bauo.fields = append([]string{field}, fields...)
	return bauo
}

// Save executes the query and returns the updated BankAccount entity.
func (bauo *BankAccountUpdateOne) Save(ctx context.Context) (*BankAccount, error) {
	return withHooks(ctx, bauo.sqlSave, bauo.mutation, bauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bauo *BankAccountUpdateOne) SaveX(ctx context.Context) *BankAccount {
	node, err := bauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bauo *BankAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := bauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bauo *BankAccountUpdateOne) ExecX(ctx context.Context) {
	if err := bauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bauo *BankAccountUpdateOne) sqlSave(ctx context.Context) (_node *BankAccount, err error) {
	_spec := sqlgraph.NewUpdateSpec(bankaccount.Table, bankaccount.Columns, sqlgraph.NewFieldSpec(bankaccount.FieldID, field.TypeInt))
	id, ok := bauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BankAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bankaccount.FieldID)
		for _, f := range fields {
			if !bankaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bankaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bauo.mutation.UserID(); ok {
		_spec.SetField(bankaccount.FieldUserID, field.TypeString, value)
	}
	if value, ok := bauo.mutation.BankName(); ok {
		_spec.SetField(bankaccount.FieldBankName, field.TypeString, value)
	}
	if value, ok := bauo.mutation.BankAccount(); ok {
		_spec.SetField(bankaccount.FieldBankAccount, field.TypeUUID, value)
	}
	if value, ok := bauo.mutation.CreatedAt(); ok {
		_spec.SetField(bankaccount.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &BankAccount{config: bauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bauo.mutation.done = true
	return _node, nil
}
