// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Point is the predicate function for point builders.
type Point func(*sql.Selector)

// PointInfo is the predicate function for pointinfo builders.
type PointInfo func(*sql.Selector)

// SubTask is the predicate function for subtask builders.
type SubTask func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
