// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BankAccountsColumns holds the columns for the "bank_accounts" table.
	BankAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bank_name", Type: field.TypeString},
		{Name: "bank_account", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BankAccountsTable holds the schema information for the "bank_accounts" table.
	BankAccountsTable = &schema.Table{
		Name:       "bank_accounts",
		Columns:    BankAccountsColumns,
		PrimaryKey: []*schema.Column{BankAccountsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BankAccountsTable,
	}
)

func init() {
}
