// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BankAccount is the predicate function for bankaccount builders.
type BankAccount func(*sql.Selector)
