Project TodoPoint {
  database_type: 'MySQL'
  Note: '''
    # Member Database
  '''
}

Table Member as Mem {
    id int [pk, increment]
    email varchar
    username varchar
    password varchar
    created_at datetime [default: `now()`]
}

Table Task as t{
    id int [pk, increment]
    title varchar
    total_status varchar
    user_id int [ref: > Mem.id]
    created_at datetime [default: `now()`]
    modified_at datetime
}

Table Subtask as st{
    id int [pk, increment]
    title varchar
    status varchar
    task_id int [ref: > t.id]
    created_at datetime [default: `now()`]
    modified_at datetime
}
