// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"todopoint/common/db/ent/member"
	"todopoint/common/db/ent/point"
	"todopoint/common/db/ent/pointinfo"
	"todopoint/common/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PointInfoQuery is the builder for querying PointInfo entities.
type PointInfoQuery struct {
	config
	ctx        *QueryContext
	order      []pointinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.PointInfo
	withPoints *PointQuery
	withUser   *MemberQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PointInfoQuery builder.
func (piq *PointInfoQuery) Where(ps ...predicate.PointInfo) *PointInfoQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PointInfoQuery) Limit(limit int) *PointInfoQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PointInfoQuery) Offset(offset int) *PointInfoQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PointInfoQuery) Unique(unique bool) *PointInfoQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PointInfoQuery) Order(o ...pointinfo.OrderOption) *PointInfoQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryPoints chains the current query on the "points" edge.
func (piq *PointInfoQuery) QueryPoints() *PointQuery {
	query := (&PointClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pointinfo.Table, pointinfo.FieldID, selector),
			sqlgraph.To(point.Table, point.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pointinfo.PointsTable, pointinfo.PointsColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (piq *PointInfoQuery) QueryUser() *MemberQuery {
	query := (&MemberClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pointinfo.Table, pointinfo.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pointinfo.UserTable, pointinfo.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PointInfo entity from the query.
// Returns a *NotFoundError when no PointInfo was found.
func (piq *PointInfoQuery) First(ctx context.Context) (*PointInfo, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pointinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PointInfoQuery) FirstX(ctx context.Context) *PointInfo {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PointInfo ID from the query.
// Returns a *NotFoundError when no PointInfo ID was found.
func (piq *PointInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pointinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PointInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PointInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PointInfo entity is found.
// Returns a *NotFoundError when no PointInfo entities are found.
func (piq *PointInfoQuery) Only(ctx context.Context) (*PointInfo, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pointinfo.Label}
	default:
		return nil, &NotSingularError{pointinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PointInfoQuery) OnlyX(ctx context.Context) *PointInfo {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PointInfo ID in the query.
// Returns a *NotSingularError when more than one PointInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PointInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pointinfo.Label}
	default:
		err = &NotSingularError{pointinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PointInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PointInfos.
func (piq *PointInfoQuery) All(ctx context.Context) ([]*PointInfo, error) {
	ctx = setContextOp(ctx, piq.ctx, "All")
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PointInfo, *PointInfoQuery]()
	return withInterceptors[[]*PointInfo](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PointInfoQuery) AllX(ctx context.Context) []*PointInfo {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PointInfo IDs.
func (piq *PointInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, "IDs")
	if err = piq.Select(pointinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PointInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PointInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, "Count")
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PointInfoQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PointInfoQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PointInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, "Exist")
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PointInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PointInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PointInfoQuery) Clone() *PointInfoQuery {
	if piq == nil {
		return nil
	}
	return &PointInfoQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]pointinfo.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.PointInfo{}, piq.predicates...),
		withPoints: piq.withPoints.Clone(),
		withUser:   piq.withUser.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithPoints tells the query-builder to eager-load the nodes that are connected to
// the "points" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PointInfoQuery) WithPoints(opts ...func(*PointQuery)) *PointInfoQuery {
	query := (&PointClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withPoints = query
	return piq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PointInfoQuery) WithUser(opts ...func(*MemberQuery)) *PointInfoQuery {
	query := (&MemberClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withUser = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TotalPoints int64 `json:"total_points,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PointInfo.Query().
//		GroupBy(pointinfo.FieldTotalPoints).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *PointInfoQuery) GroupBy(field string, fields ...string) *PointInfoGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PointInfoGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = pointinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TotalPoints int64 `json:"total_points,omitempty"`
//	}
//
//	client.PointInfo.Query().
//		Select(pointinfo.FieldTotalPoints).
//		Scan(ctx, &v)
func (piq *PointInfoQuery) Select(fields ...string) *PointInfoSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PointInfoSelect{PointInfoQuery: piq}
	sbuild.label = pointinfo.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PointInfoSelect configured with the given aggregations.
func (piq *PointInfoQuery) Aggregate(fns ...AggregateFunc) *PointInfoSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PointInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !pointinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PointInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PointInfo, error) {
	var (
		nodes       = []*PointInfo{}
		withFKs     = piq.withFKs
		_spec       = piq.querySpec()
		loadedTypes = [2]bool{
			piq.withPoints != nil,
			piq.withUser != nil,
		}
	)
	if piq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pointinfo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PointInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PointInfo{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withPoints; query != nil {
		if err := piq.loadPoints(ctx, query, nodes,
			func(n *PointInfo) { n.Edges.Points = []*Point{} },
			func(n *PointInfo, e *Point) { n.Edges.Points = append(n.Edges.Points, e) }); err != nil {
			return nil, err
		}
	}
	if query := piq.withUser; query != nil {
		if err := piq.loadUser(ctx, query, nodes, nil,
			func(n *PointInfo, e *Member) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *PointInfoQuery) loadPoints(ctx context.Context, query *PointQuery, nodes []*PointInfo, init func(*PointInfo), assign func(*PointInfo, *Point)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PointInfo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Point(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pointinfo.PointsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.point_info_points
		if fk == nil {
			return fmt.Errorf(`foreign-key "point_info_points" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "point_info_points" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (piq *PointInfoQuery) loadUser(ctx context.Context, query *MemberQuery, nodes []*PointInfo, init func(*PointInfo), assign func(*PointInfo, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PointInfo)
	for i := range nodes {
		if nodes[i].member_point_info == nil {
			continue
		}
		fk := *nodes[i].member_point_info
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_point_info" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *PointInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PointInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pointinfo.Table, pointinfo.Columns, sqlgraph.NewFieldSpec(pointinfo.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pointinfo.FieldID)
		for i := range fields {
			if fields[i] != pointinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PointInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(pointinfo.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = pointinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PointInfoGroupBy is the group-by builder for PointInfo entities.
type PointInfoGroupBy struct {
	selector
	build *PointInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PointInfoGroupBy) Aggregate(fns ...AggregateFunc) *PointInfoGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PointInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, "GroupBy")
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PointInfoQuery, *PointInfoGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PointInfoGroupBy) sqlScan(ctx context.Context, root *PointInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PointInfoSelect is the builder for selecting fields of PointInfo entities.
type PointInfoSelect struct {
	*PointInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PointInfoSelect) Aggregate(fns ...AggregateFunc) *PointInfoSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PointInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, "Select")
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PointInfoQuery, *PointInfoSelect](ctx, pis.PointInfoQuery, pis, pis.inters, v)
}

func (pis *PointInfoSelect) sqlScan(ctx context.Context, root *PointInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
